"""Session view models — list items and the full detail view a template renders.

Both are pure projections over `SessionService` (+ the persisted model's reasoning). No filesystem, no
readiness re-derivation — `status()` does that; here we only assemble what a screen shows.
"""

from __future__ import annotations

from requivo.services.sessions import SessionService
from requivo.web.viewmodels.status import readiness_view, understanding_view

# Artifact type → human label, in display order (only brief/prd are generated by the Web today, but a
# session created by the CLI may carry others, so we label them all).
ARTIFACT_LABELS = {
    "brief": "Solution assessment",
    "prd": "PRD",
    "stories": "User stories",
    "criteria": "Acceptance criteria",
    "epic": "Delivery epic",
    "release": "Release notes",
}


def _artifacts_view(status: dict) -> list[dict]:
    arts = status.get("artifacts", {})
    return [
        {"type": t, "label": ARTIFACT_LABELS.get(t, t), "revision": a["revision"],
         "filename": a["filename"], "stale": a["stale"]}
        for t, a in sorted(arts.items())
    ]


def session_list(sessions: SessionService) -> list[dict]:
    """One row per local session for the home page — status at a glance."""
    items = []
    for meta in sessions.list_sessions():
        status = sessions.status(meta.slug)
        arts = status.get("artifacts", {})
        items.append({
            "slug": meta.slug,
            "revision": meta.current_revision,
            "updated_at": meta.updated_at,
            "provider": meta.provider or "—",
            "ready": status["readiness"]["ready"],
            "blocking": len(status["readiness"]["blocking_slots"]),
            "artifact_count": len(arts),
            "stale_count": sum(1 for a in arts.values() if a["stale"]),
        })
    return items


def session_detail(sessions: SessionService, slug: str) -> dict:
    """The full session screen: understanding, readiness, priority questions, the persisted reasoning
    (decisions / challenges / opportunities), remaining gaps, and artifacts."""
    status = sessions.status(slug)
    model = sessions.load_model(slug)
    return {
        "slug": slug,
        "revision": status.get("revision"),
        "readiness": readiness_view(status),
        "understanding": understanding_view(status),
        "questions": status.get("questions", []),
        "summary": status.get("summary", {}),
        "remaining_gaps": status.get("remaining_gaps", []),
        "context_cards": status.get("context_cards"),
        "artifacts": _artifacts_view(status),
        "decisions": [d.model_dump() for d in model.decisions],
        "challenges": [c.model_dump() for c in model.challenges],
        "opportunities": [o.model_dump() for o in model.opportunities],
    }
