from __future__ import annotations

from requivo.core.analysis import _label, _readiness_blockers
from requivo.core.contracts import PRD, AcceptanceCriteria, Brief, EngineOutput, Epic, ReleaseNotes, ScenarioKind

_KIND_TAG = {
    ScenarioKind.happy_path: "Happy path",
    ScenarioKind.edge_case: "Edge case",
    ScenarioKind.error: "Error",
    ScenarioKind.permission: "Permission",
}


def _cell(text: str) -> str:
    """Make text safe for a Markdown table cell: a literal `|` closes the cell and a newline ends the
    row, so a requirement containing either would break the table. Escape one, flatten the other."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def brief_markdown(out: EngineOutput, brief: Brief) -> str:
    """Render the solution assessment as a shareable Markdown document — the deliverable an interface
    saves and a reader downloads. Mirrors the terminal assessment (the judgment: decisions, contested
    premises, complexity, risks, ranked opportunities) in PM language. Slot ids and internal signals
    (completeness, confidence) never appear — blocking topics are shown by their human labels, matching
    the Voice rule the LLM prose already follows."""
    blockers = [_label(sid) for sid in _readiness_blockers(out)]
    draft = " — Draft: blocking unknowns remain" if blockers else ""
    md: list[str] = [f"# Solution Assessment{draft}", "",
                     "> Senior-PM judgment of the requirements model — generated by Requivo", ""]

    def section(heading: str, lines: list[str]) -> None:
        if lines:
            md.extend([f"## {heading}", "", *lines, ""])

    summary = []
    if brief.problem:
        summary.append(f"**Problem:** {brief.problem}")
    if brief.solution:
        summary.append(f"**Solution:** {brief.solution}")
    summary.append(f"**Complexity:** {brief.complexity.value}"
                   + (f" — {'; '.join(brief.complexity_reasons)}" if brief.complexity_reasons else ""))
    if brief.cost_driver:
        summary.append(f"**Main cost driver:** {brief.cost_driver}")
    section("Executive summary", summary)

    section("Introduces", [f"- {i}" for i in brief.introduces])

    decisions: list[str] = []
    for d in brief.decisions:
        line = f"- **{d.decision}**"
        if d.why:
            line += f" — {d.why}"
        decisions.append(line)
        if d.alternative:
            decisions.append(f"  - _Alternative weighed:_ {d.alternative}")
        if d.tradeoff:
            decisions.append(f"  - _Trade-off accepted:_ {d.tradeoff}")
    section("Design decisions", decisions)

    challenges: list[str] = []
    for c in brief.challenges:
        challenges += [f"### {c.headline}",
                       f"- **Premise:** {c.premise}",
                       f"- **Alternative:** {c.alternative}",
                       f"- **Consequence:** {c.consequence}",
                       f"- **Recommendation:** {c.recommendation}", ""]
    section("Challenges to the premise", challenges)

    section("Main risks", [f"- {r}" for r in brief.risks])
    section("Opportunities", [
        f"- **{o.text}** (leverage: {o.leverage.value})"
        + (f" — reaches {', '.join(o.modules)}" if o.modules else "")
        for o in brief.opportunities])
    section("Next steps", [f"- {s}" for s in brief.next_steps])
    section("Open decisions", [f"- {d}" for d in brief.open_decisions])
    section("Ready for implementation",
            [f"Blocking unknowns: {' · '.join(blockers)}" if blockers
             else "No blocking unknowns — ready for implementation."])

    return "\n".join(md).rstrip() + "\n"


def prd_markdown(prd: PRD) -> str:
    """Render a PRD as a clean, shareable Markdown document."""
    out: list[str] = [f"# {prd.title}", "", "> Product Requirements Document — generated by Requivo", ""]

    def section(heading: str, lines: list[str]) -> None:
        if lines:
            out.extend([f"## {heading}", "", *lines, ""])

    def bullets(items: list[str]) -> list[str]:
        return [f"- {i}" for i in items]

    if prd.summary:
        section("Summary", [prd.summary])
    if prd.problem:
        section("Problem", [prd.problem])
    section("Goals", bullets(prd.goals))
    section("Users & roles", bullets(prd.users))

    scope: list[str] = []
    if prd.in_scope:
        scope += ["**In scope**", "", *bullets(prd.in_scope), ""]
    if prd.out_of_scope:
        scope += ["**Out of scope**", "", *bullets(prd.out_of_scope)]
    section("Scope", scope)

    if prd.requirements:
        rows = ["| ID | Requirement | Priority |", "|----|-------------|----------|"]
        rows += [f"| {_cell(r.id)} | {_cell(r.requirement)} | {r.priority.value.capitalize()} |"
                 for r in prd.requirements]
        section("Functional requirements", rows)

    section("Workflow", [f"{i}. {step}" for i, step in enumerate(prd.workflow, 1)])
    section("Business rules", bullets(prd.business_rules))
    section("Permissions", bullets(prd.permissions))
    section("Integrations & notifications", bullets(prd.integrations))
    section("Edge cases", bullets(prd.edge_cases))
    section("Acceptance criteria", [f"- [ ] {a}" for a in prd.acceptance_criteria])
    section("Assumptions", bullets(prd.assumptions))
    section("Open questions", bullets(prd.open_questions))
    section("Risks", bullets(prd.risks))

    return "\n".join(out).rstrip() + "\n"


def criteria_markdown(ac: AcceptanceCriteria) -> str:
    """Render acceptance criteria as a Given/When/Then Markdown checklist for recette."""
    out: list[str] = [f"# {ac.title}", "", "> Acceptance criteria — generated by Requivo", ""]

    for feature in ac.features:
        out += [f"## {feature.name}", ""]
        for s in feature.scenarios:
            out.append(f"### [ ] {s.id} — {s.title}  _{_KIND_TAG.get(s.kind, s.kind.value)}_")
            out.append("")
            for i, g in enumerate(s.given):
                out.append(f"- **{'Given' if i == 0 else 'And'}** {g}")
            if s.when:
                out.append(f"- **When** {s.when}")
            for i, t in enumerate(s.then):
                out.append(f"- **{'Then' if i == 0 else 'And'}** {t}")
            out.append("")

    if ac.open_questions:
        out += ["## Open questions", "", *[f"- {q}" for q in ac.open_questions], ""]

    return "\n".join(out).rstrip() + "\n"


def epic_markdown(epic: Epic) -> str:
    """Render a delivery epic as Markdown: goal, scope, then a checklist of trackable issues."""
    out: list[str] = [f"# Epic: {epic.title}", "", "> Delivery epic — generated by Requivo", ""]
    if epic.milestone:
        out += [f"**Milestone:** {epic.milestone}", ""]
    if epic.goal:
        out += [f"**Goal:** {epic.goal}", ""]
    if epic.business_value:
        out += [f"**Business value:** {epic.business_value}", ""]

    if epic.in_scope:
        out += ["## In scope", "", *[f"- {i}" for i in epic.in_scope], ""]
    if epic.out_of_scope:
        out += ["## Out of scope", "", *[f"- {i}" for i in epic.out_of_scope], ""]

    if epic.issues:
        out += ["## Issues", ""]
        for issue in epic.issues:
            out.append(f"### [ ] {issue.id} — {issue.title}")
            out.append("")
            meta: list[str] = []
            if issue.labels:
                meta.append("**Labels:** " + ", ".join(f"`{lab}`" for lab in issue.labels))
            if issue.depends_on:
                meta.append("**Depends on:** " + ", ".join(issue.depends_on))
            if meta:
                out += [" · ".join(meta), ""]
            if issue.description:
                out += [issue.description, ""]

    if epic.open_questions:
        out += ["## Open questions", "", *[f"- {q}" for q in epic.open_questions], ""]

    return "\n".join(out).rstrip() + "\n"


def release_markdown(rn: ReleaseNotes) -> str:
    """Render client-facing release notes as a clean, shareable Markdown announcement."""
    heading = f"# {rn.title}" + (f" — {rn.version}" if rn.version else "")
    out: list[str] = [heading, "", "> Release notes — generated by Requivo", ""]

    def section(heading: str, lines: list[str]) -> None:
        if lines:
            out.extend([f"## {heading}", "", *lines, ""])

    if rn.summary:
        out += [rn.summary, ""]
    section("What's new", [f"- {h}" for h in rn.highlights])
    section("Not included yet", [f"- {lim}" for lim in rn.known_limitations])
    section("Before you start", [f"- {n}" for n in rn.notes])

    return "\n".join(out).rstrip() + "\n"
